root: true
env:
  node: true
extends:
  - "plugin:vue/essential"
  - "@vue/standard"
  - "@vue/typescript/recommended"
parserOptions:
  ecmaVersion: 2020
rules:
  'no-console': 'warn'
  'no-debugger': 'warn'